### ISSUE TITLE
Make tech stack decisions

### ISSUE THREAD

**Issue by matty22** [lacyjpr/media#15]

**Comment by matty22** [comment]
I started listing some things we know for sure/discussed earlier today. Lots of unknowns here still:

* Client
  1. FE JS Framework: React
  2. SCSS with BEM
  3. Testing: Jest? Enzyme
  4. Bundler/Build tool: CRA/Webpack
  5. WYSIWYG editor: SlateJS

* Server
  1. Express
  2. Node
  3. Other needs TBD

* Database
  1. PostgreSQL
  2. pg
  3. Other needs TBD

* Hosting
  1. Heroku

* Miscellaneous
  1. CI/CD: Travis CI
  2. Authentication: Passport.js
  3. Diagramming: Draw.io

**Comment by lacyjpr** [comment]
CRA vs Kornil's Simple React App

**Comment by lacyjpr** [comment]
Hosting? https://devcenter.heroku.com/categories/heroku-postgres

**Comment by matty22** [comment]
I've never used AWS or Azure. Might be cool to consider using one of those for hosting to learn how to do it.

**Comment by P1xt** [comment]
You might also consider [Travis CI](https://travis-ci.org/) for auto-deploy no matter where you eventually decide to host. Having it run your tests and lints and whatnot then just deploy when you push/merge to master is a massive help in the development process, not just because you just merge-gogettea, also because it ensures that only good builds get deployed.

**Comment by lacyjpr** [comment]
Cookies vs JWTs

**Comment by lacyjpr** [comment]
Prettier?

**Comment by matty22** [comment]
Some sort of diagramming tool to keep a flowchart of database relationships in visual form?

**Comment by lacyjpr** [comment]
SCSS or CSS

**Comment by matty22** [comment]
On the topic of CSS:

* CSS modules
* CSS in JS
* Trying to keep namespaced CSS organized
